# Generated by Django 4.2.20 on 2026-04-27 21:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('deal_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=10, verbose_name='Тип сделки')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь, м²')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Главное фото')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('sold', 'Продан'), ('rented', 'Сдан')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s()]{7,20}$', 'Введите корректный телефон.')], verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Заявка на просмотр',
                'verbose_name_plural': 'Заявки на просмотр',
                'ordering': ['-created_at'],
            },
        ),
    ]
